# Generated by Django 4.2.2 on 2025-03-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athleteID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('biography', models.CharField(max_length=1000)),
                ('smLinks', models.CharField(max_length=500)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coachID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('windSpeed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('place', models.CharField(max_length=200)),
                ('club', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('eventName', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
                ('mark', models.CharField(choices=[('60', '60'), ('100', '100'), ('200', '200'), ('400', '400'), ('800', '800'), ('1500', '1500'), ('3000', '3000'), ('5000', '5000'), ('10000', '10000'), ('60H', '60 Hurdles'), ('100H', '100 Hurdles'), ('110H', '110 Hurdles'), ('400H', '400 Hurdles'), ('3000SC', '3000 SC'), ('4100R', '4×100 Relay'), ('4400R', '4×400 Relay'), ('HM', 'Half Marathon'), ('M', 'Marathon'), ('20KW', '20K Walk'), ('PENT', 'Pentathlon'), ('HEPT', 'Heptathlon'), ('OCTA', 'Octathlon'), ('DECA', 'Decathlon'), ('HJ', 'High Jump'), ('LJ', 'Long Jump'), ('TRJ', 'Triple Jump'), ('PV', 'Pole Vault'), ('DISCUS', 'Discus'), ('JAVE', 'Javelin'), ('HAM', 'Hammer'), ('SHOT', 'Shot Put'), ('80', '80 Metres'), ('1000', '1000 Metres'), ('1200', '1200 Metres'), ('80H', '80 Hurdles'), ('BT', 'Ball Throw')], max_length=10)),
                ('age', models.CharField(choices=[('OPEN', 'Open'), ('U-17', 'Under-17'), ('U-15', 'Under-15'), ('U-13', 'Under-13'), ('U-11', 'Under-11'), ('U-09', 'Under-9')], max_length=5)),
                ('personalBest', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
