# Generated by Django 4.2.2 on 2025-03-12 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('athleteID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dob', models.DateField()),
                ('biography', models.CharField(blank=True, max_length=1000, null=True)),
                ('smLinks', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(choices=[('60M', '60 Meters'), ('80M', '80 Meters'), ('100M', '100 Meters'), ('200M', '200 Meters'), ('400M', '400 Meters'), ('800M', '800 Meters'), ('1000M', '1000 Meters'), ('1200M', '1200 Meters'), ('1500M', '1500 Meters'), ('3000M', '3000 Meters'), ('5000M', '5000 Meters'), ('10000M', '10000 Meters'), ('60H', '60 Hurdles'), ('100H', '100 Hurdles'), ('110H', '110 Hurdles'), ('400H', '400 Hurdles'), ('3000SC', '3000 SC'), ('4100R', '4×100 Relay'), ('4400R', '4×400 Relay'), ('HM', 'Half Marathon'), ('M', 'Marathon'), ('20KW', '20K Walk'), ('PENT', 'Pentathlon'), ('HEPT', 'Heptathlon'), ('OCTA', 'Octathlon'), ('DECA', 'Decathlon'), ('HJ', 'High Jump'), ('LJ', 'Long Jump'), ('TRJ', 'Triple Jump'), ('PV', 'Pole Vault'), ('DISCUS', 'Discus'), ('JAVE', 'Javelin'), ('HAM', 'Hammer'), ('SHOT', 'Shot Put'), ('80H', '80 Hurdles'), ('BT', 'Ball Throw')], max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.AutoField(primary_key=True, serialize=False)),
                ('windSpeed', models.DecimalField(decimal_places=1, max_digits=3)),
                ('place', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=10)),
                ('age', models.CharField(choices=[('OPEN', 'Open'), ('U-23', 'Under-23'), ('U-20', 'Under-20'), ('U-18', 'Under-18'), ('U-17', 'Under-17'), ('U-15', 'Under-15'), ('U-13', 'Under-13'), ('U-11', 'Under-11'), ('U-09', 'Under-9')], max_length=5)),
                ('club', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('personalBest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season', models.IntegerField(choices=[(2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019')])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='webApp.event')),
            ],
        ),
    ]
