# Generated by Django 4.2.2 on 2025-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_athleteprofile_alter_match_athlete_alter_match_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.CharField(choices=[('60M', '60 Meters'), ('80M', '80 Meters'), ('100M', '100 Meters'), ('200M', '200 Meters'), ('400M', '400 Meters'), ('800M', '800 Meters'), ('1000M', '1000 Meters'), ('1200M', '1200 Meters'), ('1500M', '1500 Meters'), ('3000M', '3000 Meters'), ('5000M', '5000 Meters'), ('10000M', '10000 Meters'), ('60H', '60 Hurdles'), ('100H', '100 Hurdles'), ('110H', '110 Hurdles'), ('400H', '400 Hurdles'), ('3000SC', '3000 SC'), ('4100R', '4×100 Relay'), ('4400R', '4×400 Relay'), ('HM', 'Half Marathon'), ('M', 'Marathon'), ('20KW', '20K Walk'), ('PENT', 'Pentathlon'), ('HEPT', 'Heptathlon'), ('OCTA', 'Octathlon'), ('DECA', 'Decathlon'), ('HJ', 'High Jump'), ('LJ', 'Long Jump'), ('TRJ', 'Triple Jump'), ('PV', 'Pole Vault'), ('DISCUS', 'Discus'), ('JAVE', 'Javelin'), ('HAM', 'Hammer'), ('SHOT', 'Shot Put'), ('80H', '80 Hurdles'), ('BT', 'Ball Throw')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
