# Generated by Django 4.2.2 on 2025-03-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_athleteprofile_name_alter_match_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='webApp.athleteprofile'),
        ),
    ]
