# Generated by Django 4.2.2 on 2025-03-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_alter_athleteprofile_name_alter_match_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
